---
- name: Prepare homelab server
  hosts: homelab
  become: true

#  vars:
#    application_name: production-server

  tasks:
#    - name: Show hostname
#      ansible.builtin.command: hostname
      
    - name: Install required packages
      ansible.builtin.apt:
        name: 
          - htop
          - curl
          - nginx
          - btop
          - neofetch
          - mc
        state: present
        update_cache: true

    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Ensure nginx is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Create application directory
      ansible.builtin.file:
        path: /opt/homelab
        state: directory
        owner: automation
        group: automation
        mode: '0755'

    - name: Create application info file
      ansible.builtin.copy:
        dest: /opt/homelab/info.txt
        content: |
          This server is managed by Ansible.
          Host: homelab-server-01
          {{ application_name }}
        owner: automation
        group: automation
        mode: '0644'
    
    - name: Create server info file from Template
      ansible.builtin.template:
        src: info2.txt.j2
        dest: /opt/homelab/info2.txt
        owner: automation
        group: automation
        mode: '0644'

    - name: Create handler test file
      ansible.builtin.copy:
        content: |
          Handler test
          Application : {{ application_name }}
        dest: /opt/homelab/handler-test.txt
        owner: automation
        group: automation
        mode: '0644'
      notify: Handler test

    - name: Configure nginx
      ansible.builtin.template:
        src: nginx-default.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Reload nginx
      
  
  handlers:
    - name: Handler test
      ansible.builtin.debug:
        msg: "The handler was triggered!"

    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
        