- name: Create Compose application directory
  ansible.builtin.file:
    path: "{{ compose_dozzle_directory }}"
    state: directory
    mode: "0755"

- name: Deploy Compose file
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: "{{ compose_dozzle_directory }}/compose.yaml"
    mode: "0644"

- name: Create Monitoring network
  community.docker.docker_network:
    name: monitoring
    state: present

- name: Create Dozzle Data Volume
  community.docker.docker_volume:
    name: dozzle_data
    state: present

- name: Start Compose application
  community.docker.docker_compose_v2:
    project_src: "{{ compose_dozzle_directory }}"
    state: present