services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    
    ports:
      - "3001:3001"
    
    volumes:
      - uptime_kuma_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - database-net
      - monitoring

volumes:
  uptime_kuma_data:
    external: true
    name: uptime_kuma_data

networks:
  database-net:
    external: true
    name: database-net

  monitoring:
    external: true
    name: monitoring